const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION_ID"Byte;;;eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiR0tBdjg1Vm95RmZUWG1iV09lWFUyR3BBTHN3YVZjblo2di9Pcmc5WjBYUT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoibmxzbTRGelloNWV0SXZkN0VWQXFrem5weEZ0bzJDd1JiUWlHMzdicFlGMD0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJRRHhJNGIwR3BEeU5maVZBK09xbG1xNFIveXpXZ0F1RjEyY25JVG0yZWtNPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJGajhpRnpBa1pqQk5nUXQxZ0ZVR2U5bVprVTRCanFsTEFZWlZETEs0aHp3PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImtBQ2hoSTdMemgzWFo1UGkyMGlKTkhoZkJ0aGZVaEMxK24yTVRWVG9jR2M9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjhuakdkbmVZcVF6a1c1cG9rbWR4YlZLVVd3SHhVMFlaUWp5Mi9pdWhSalU9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUUk0Q0Jocng2VU41UVVxK2N3MVlCc2NUb3BKL1lhVHc5U0NIT1pYaU1XND0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoic0FoQnF3NXQ4eGJVQk02YUZEVzlWaTdGejdXSi9YY1R2Yk9SeEYzYzZsYz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImQvUmM2MER1MXRXVXdPZmZZRzhGN0tXd2ZTMGtsSERJMzBmVnBLTHVtNG5sUE5QdHNac2I5dmlWLzZOeWtEUXIzUFN6SE5NdVh5akV5VnpYNjFLcGh3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjAxLCJhZHZTZWNyZXRLZXkiOiI5ZUFRbmVINTg2V2p6aG1BN29CSlRBRjB0MFRyOWxRSjFsQmpGdndsSWxvPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjI1NDc5NDExMzc4M0BzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiJCMDhEMjJGODNBMEI1NzAwQjI0MkRFQjMxNTg5NEVGNCJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzM2MDU4NDE4fSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyNTQ3OTQxMTM3ODNAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiOEEzODRCOEU3OTk0NUE5NjVDNkIzMUQxMDgzQkZBMUMifSwibWVzc2FnZVRpbWVzdGFtcCI6MTczNjA1ODQyNH1dLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sImRldmljZUlkIjoid2JlYWVTUW5TbTZQdmV5dTFlLXNpQSIsInBob25lSWQiOiI4YWZhOWRiYS1mZjRiLTQ1M2UtOTRlYy04YjhiMGEwNmY1YjIiLCJpZGVudGl0eUlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoienMvR0ZjZ0c3VDJiNjhhSjQ4YWdIMUlVdnZZPSJ9LCJyZWdpc3RlcmVkIjp0cnVlLCJiYWNrdXBUb2tlbiI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlZUbWtpVGVGK2l5enZ2TENPV0dISlBIK3UrTT0ifSwicmVnaXN0cmF0aW9uIjp7fSwicGFpcmluZ0NvZGUiOiI3V0E0QlZCMiIsIm1lIjp7ImlkIjoiMjU0Nzk0MTEzNzgzOjVAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoifioqUVXCo3biiIV+O+KBoCnimqDvuI8ifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ0wrcnBKb0ZFSjNNNkxzR0dBSWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6IkI2aHdLTXFDT2h6aUtMTGw5L2pFUmxiS2Y0VTJiQmJsdnFSdFdNNFB6bHc9IiwiYWNjb3VudFNpZ25hdHVyZSI6ImdzVzR5MFVERWJZbHdsVXhBdnkwejhKY29ZdDY5bzhjakFna3hnR1JxbFBLVElWM3R2RHJ2eXBkb05IQzlsZmM4MmgvZkYrL3pXMjlpc1pzY3hlR0JBPT0iLCJkZXZpY2VTaWduYXR1cmUiOiIya3VUaWNpQjRyRU5ISktYYUw4TU1rZ3F5M0N5cC9RQmZoak5Qa0NKcDFqWXN3ZUpOSXJ3UEQxVUNvSkk0aEpQTGlBTGNLS2h2NWpQVTVpcmtNT3NnQT09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjI1NDc5NDExMzc4Mzo1QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlFlb2NDaktnam9jNGlpeTVmZjR4RVpXeW4rRk5td1c1YjZrYlZqT0Q4NWMifX1dLCJwbGF0Zm9ybSI6ImFuZHJvaWQiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MzYwNTg0MTEsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBRFl2In0=: process.env.SESSION_ID || "",
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "public",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "254794113783",
  "OWNER_NAME": process.env.OWNER_NAME || "quevo",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'true',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'true',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'true',
  "AUTO_REACT": process.env.AUTO_REACT === 'true',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "254",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'true'
};
